### ISSUE TITLE
make file fatal error: './openssl/sha.h' file not found (mac ARM M1 Pro)

### ISSUE THREAD

**Issue by astral-matrix** [shoggoth-systems/shoggoth#1]
Fatal error when running make script for Shoggoth source on Mac ARM M1 Pro.
version:  shoggoth-source-v0.1.5 
sha256: 2f0ea26dcdbc981f5df30528653f1ae95c93f6fe017a838aed49177b28d8be11

Device:
Macbook Pro 14" 2021 Apple M1 Pro
macOS 13.4 (22F66) Ventura

Openssl version:
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)

Console log below:

dad$ make
Building Shoggoth (flat)...
./src/openssl/openssl.c:12:10: fatal error: './openssl/sha.h' file not found
#include "./openssl/sha.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build-objects-flat] Error 1

**Comment by thenetrunna** [comment]
Try installing openssl:

`brew install openssl`

**Comment by thenetrunna** [comment]
Try building my fork: https://github.com/thenetrunna/shoggoth

**Comment by thenetrunna** [comment]
Fixed in #9
