### ISSUE TITLE
Make Test Failing for Manjaro Linux

### ISSUE THREAD

**Issue by snow-blade** [shoggoth-systems/shoggoth#19]
I tried to run `make test` but I consistently get this error: 
```Building Shoggoth (debug)...
Creating Shoggoth static lib (debug)...
/usr/bin/ld: cannot find ../../target/sonic-sanitized.a: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:133: build-unit-tests] Error 1
make: *** [makefiles/test.mk:10: build-unit-tests] Error 2
```
I figured it has something to do with the fact that `make build` only installs packages for debian-based systems. 

Am I missing something?

**Comment by thenetrunna** [comment]
Do you have the latest changes on 'master' branch?

**Comment by snow-blade** [comment]
Yes! I do have the latest changes. I made sure to clone the repo and replicate the error at least 5 times before opening the issue.

**Comment by thenetrunna** [comment]
Are you running the make command on multiple threads?

**Comment by snow-blade** [comment]
Multiple CPU threads? No, I do not think I am. 
Also, my bad for assuming `make build` installs packages. It seems like the setup-linux function in the makefile is not called during the building process.

**Comment by samsararider** [comment]
@snow-blade try `make && make build-sanitized && make test`. I think some makefile dependencies are not fully written out.

**Comment by thenetrunna** [comment]
You have to run `make dev` before running `make test`

**Comment by thenetrunna** [comment]
`make dev` builds `sonic-sanitized.a`

**Comment by thenetrunna** [comment]
Please note that tests are mostly broken.

**Comment by snow-blade** [comment]
I ran make dev.
This is what I have so far:
```Building Shoggoth (debug)...
Creating Shoggoth static lib (debug)...
/usr/bin/ld: ../../target/camel.a(camel.o): in function `__read_file':
/home/freeman/shoggoth/lib/camel/./src/camel.c:64:(.text+0x1a7): undefined reference to `read_file_to_string'
/usr/bin/ld: /home/freeman/shoggoth/lib/camel/./src/camel.c:64:(.text+0x20d): undefined reference to `__unwrap'
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:133: build-unit-tests] Error 1
make: *** [makefiles/test.mk:10: build-unit-tests] Error 2
```

**Comment by thenetrunna** [comment]
Fixed in latest changes on `master` branch

**Comment by samsararider** [comment]
@snow-blade did the fix worked for you? Can this be closed? 🙂

**Comment by thenetrunna** [comment]
replaced by #39
