### ISSUE TITLE
Ability to download binary files through Explorer

### ISSUE THREAD

**Issue by samsararider** [shoggoth-systems/shoggoth#25]
When you're browsing a profile in Explorer and it has a 'binary file', there should be an option to download it. 

Currently it just says "binary file" without showing its contents.

**Comment by thenetrunna** [comment]
Not sure if we want to allow downloading content from the browser. The user should be able to obtain it by cloning the resource

**Comment by samsararider** [comment]
Right. In that case, say 'Binary file. Use `shog client clone SHOGX` to clone'.

**Comment by thenetrunna** [comment]
You are suggesting allowing the client to download individual files from a resource?

**Comment by samsararider** [comment]
Oh right, I see. Nah, that sounds like too much.

Just changing the copy is enough. I think it could be a great call to action:

"Binary file. Clone the profile using `shog client clone SHOGX` to view this and other files!"

**Comment by thenetrunna** [comment]
#40 allows the user to download a resource from the explorer. Should that close this issue?

**Comment by samsararider** [comment]
@thenetrunna yeah this should suffice i think
