### ISSUE TITLE
`make install` should not blow away ~/shoggoth directory which may have production config

### ISSUE THREAD

**Issue by samsararider** [shoggoth-systems/shoggoth#27]
I think an easy fix is to move the folder to `~/shoggoth_old_1`. Similarly how Firefox does it with 'Old Firefox Data' when refreshing a profile. 

Or upgrade the directory more gracefully, but that could be complicated.

**Comment by thenetrunna** [comment]
`~/shoggoth_old` should be sufficient. Are you making PR?

**Comment by samsararider** [comment]
@thenetrunna not making a PR, someone else can take it! 🙂

**Comment by thenetrunna** [comment]
> @thenetrunna not making a PR, someone else can take it! 🙂

Alright! I'm on it!
