### ISSUE TITLE
RedisJSON license

### ISSUE THREAD

**Issue by Aspie96** [shoggoth-systems/shoggoth#3]
I like the idea behind Shoggoth. I think a decentralized and censorship-resistant way to share ML models, based on free and open source software, is a worthwhile goal. There was a lot of discussion around it and I applaud Shoggoth Systems for actually doing it.

I think it's important to note, however, that one dependency in particular is not FLOSS. I'm referring to RedisJSON, which is merely source available and released under a dual proprietary licensing scheme (where both licenses are proprietary): https://github.com/RedisJSON/RedisJSON/blob/master/LICENSE.txt

The licensing of Shoggoth might lead users to think that it's 100% free and open source, without being aware of the conditions of a proprietary license.

For this reason, I think the presence of RedisJSON, as well as its licensing, should be documented or at least mentioned somewhere prominent for as long as it's a dependency.

I also think it's somewhat unfortunate to have a proprietary dependency in an otherwise fully free program, because software freedom matters.

**Comment by thenetrunna** [comment]
The documentation has been updated to clarify that RedisJSON is proprietary.
This will be included in the next minor release.

**Comment by Aspie96** [comment]
Thanks a lot, Netrunner.

Of course, I was not implying you hadn't checked the licenses and, in fact, I very much appreciate that you have been careful on the matter.

Of course, I do not know what your requirements are in terms of licensing: my comment is based on the largely agreed standard for free an open source software.

As documented, Redis refrains from defining the license as open source, so I'm not denying anything they are saying, or implying anything bad from their part.

The RedisJSON licensing is documented [here](https://redis.com/legal/licenses/). The SSPL, and its status as a non-FLOSS license, has already been widely discussed publicly. As for the [Redis Source Available License v2 (RSALv2)](https://redis.com/legal/rsalv2-agreement/), it expressly states the following:

> You may not make the functionality of the software or a modified version available to third parties as a service, or distribute the software or a modified version in a manner that makes the functionality of the software available to third parties.

Of course, it's a dual license. The user can pick either the SSPL or the RSA, as they wish, but it will be effectively proprietary in both cases.

Your plan for a replacement is interesting, as it can be quite valuable for different projects too, even if partial.

**Comment by thenetrunna** [comment]
#26 replaces redis and redisjson with a new database called ShogDB.
