### ISSUE TITLE
Upgrade redis to at least `7.2.2` to fix build on macOS 13

### ISSUE THREAD

**Issue by samsararider** [shoggoth-systems/shoggoth#4]
We need this https://github.com/redis/redis/pull/12611 fix to get redis to compile on macOS 13. 

@thenetrunna I can import redis 7.2.2 into the repo, but it probably would be a big diff (hard to rebview), so would be better for you to do it?

**Comment by samsararider** [comment]
Can also upgrade redis directly to the https://github.com/redis/redis/commit/a2b0701d2 commit which is the merge commit for macOS 13 fix

**Comment by thenetrunna** [comment]
I'll upgrade redis to `7.2.3` (latest release). Should fix the issue.

**Comment by thenetrunna** [comment]
Redis has been upgraded to `7.2.3` in `master` branch.

**Comment by samsararider** [comment]
@thenetrunna your Redis upgrade to `7.2.3` fixed the macOS 13 build issue for me 🎉  Thanks!

**Comment by thenetrunna** [comment]
> @thenetrunna your Redis upgrade to `7.2.3` fixed the macOS 13 build issue for me 🎉 Thanks!

Awesome!!
