### ISSUE TITLE
lsat error

### ISSUE THREAD

**Issue by nspeer12** [shoggoth-systems/shoggoth#7]
I'm trying to publish my client with a single git repo inside of shoggoth-profile/code, and I get the following error: 

I'm using the latest version of shoggoth built from source ([b0af854](https://github.com/shoggoth-systems/shoggoth/commit/b0af85455c34276bb4090edd5e6e01a6d64803b9))

```
$ shog client publish
[INFO]: Initializing client
[INFO]: Using default runtime path: /home/.../...


[INFO]: Publishing profile ...
lstat: No such file or directory
Error: lstat error
```

System Details
OS: Pop!_OS 22.04 LTS x86_64 
Host: MS-7C91 2.0 
Kernel: 6.5.6-76060506-generic

**Comment by nspeer12** [comment]
```
[INFO]: Publishing profile ...
lstat: No such file or directory
EXIT with status 1 at ./src/main.c:49:
Error: lstat error
```

**Comment by thenetrunna** [comment]
Hey @nspeer12 

Can you try building the master branch and installing from scratch?

Note that it'll delete your shoggoth profile and you'd have to create a new profile.
Alternatively, you can backup your keys if you want to retain your profile.

**Comment by nspeer12** [comment]
I built from master and it's working. Thanks

**Comment by thenetrunna** [comment]
Great!
